### ISSUE TITLE
Article Tags

### ISSUE THREAD

**Issue by itsthomthomob** [Developer-DUCS/TheDruryMirrorApp#27]
**Issue Proposition**
-To add tags such as "Local", "National", "Global", etc. to articles

**Issue Context**
- We have pages on the mobile application that require these tags for filtering different articles
- We sort of promised this to Drury Mirror during our Sprint 6 / Final presentation last semester

**Implementation** 
- It won't be that difficult to implement, just a dropdown of chosen tags, then apply them to a "tag" column separated by commas or an array object

**Comment by tnield** [comment]
Ill handle adding the drop down box on the portal and working with sam to add the tags to. the SQL database. Will create a new branch for the edits.

**Comment by tnield** [comment]
Article tags is working, but a delete new tags and dealing with two word tags needs to still be done.
