### ISSUE TITLE
Connecting Website to Mobile App

### ISSUE THREAD

**Issue by tnield** [Developer-DUCS/TheDruryMirrorApp#8]
This is for those working on connecting the website to the mobile and getting published articles to be visible on the mobile app.

**Comment by itsthomthomob** [comment]
**To Do:**
- Write an API file to connect the mobile app to the MySQL server and fetch the articles OR
- Write an API file on the Web Portal for fetching articles, call this API in the Mobile Dev branch
- - Requires a domain on the web portal to fetch from, but this provides a layer of security from the Mobile App -> Web Portal then to the MySQL server
