### ISSUE TITLE
Comment Editor Highlighting

### ISSUE THREAD

**Issue by tnield** [Developer-DUCS/TheDruryMirrorApp#9]
The problem is that when someone goes to highlight a new comment, if that word has multiple instances the first instance will be highlighted not necessarily the one the user wants. 

This happens because the current code is using string matching to insure the correct thing is commented. What needs to happen is that index matching needs to be included as well. 

Adding index matching shouldn't be difficult because the index for the beginning and the end of the highlighted section is recorded earlier in the code, but for whatever reason it is not working.

**Comment by srudqvist** [comment]
This should be fixed now, please take a look at it in the Sam branch and try to find cases where it breaks
